version: '2'

services:

  database:
      image: mysql:5.7
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=secret"
      volumes:
        - ~/backup/database/mysql:/var/lib/mysql
      ports:
        - "3306:3306"





